const { ExpenseCategory } = require('../models');

module.exports = {
  up: async () => {
    const categories = [
      { code: 1, name: 'الأسماك' },
      { code: 2, name: 'الخضار والفواكه' },
      { code: 3, name: 'الزيت' },
      { code: 4, name: 'مواد الطبخ' },
      { code: 5, name: 'الأرز' },
      { code: 6, name: 'البهارات' },
      { code: 7, name: 'البطاطس' },
      { code: 8, name: 'المقبلات' },
      { code: 9, name: 'المجمدات' },
      { code: 10, name: 'المشروبات' },
      { code: 11, name: 'الخبز' },
      { code: 12, name: 'إعاشة عمال' },
      { code: 13, name: 'الثلج' },
      { code: 14, name: 'الغاز' },
      { code: 15, name: 'الفحم' },
      { code: 16, name: 'الوقود' },
      { code: 17, name: 'الصيانة العامة' },
      { code: 18, name: 'السيارات' },
      { code: 19, name: 'الصرف الصحي' },
      { code: 20, name: 'النثريات' },
      { code: 21, name: 'الرسوم الحكومية' },
      { code: 22, name: 'الرسوم البلدية' },
      { code: 23, name: 'رسوم الأقامات' },
      { code: 24, name: 'المخالفات الحكومية' },
      { code: 25, name: 'المخالفات المرورية' },
      { code: 26, name: 'التأمينات الاجتماعية' },
      { code: 27, name: 'الزكاة والدخل' },
      { code: 28, name: 'ضريبة القيمة المضافة' },
      { code: 29, name: 'الاستثمارات العامة' },
      { code: 30, name: 'صدقات لوجه الله' },
      { code: 31, name: 'أصول المطعم' },
      { code: 32, name: 'أدوات مكتبية' },
      { code: 33, name: 'أدوات مطبخ' },
      { code: 34, name: 'الأثاث' },
      { code: 35, name: 'الإنشاءات والتجديدات' },
      { code: 36, name: 'مصروفات المستودع' },
      { code: 37, name: 'فواتير الكهرباء' },
      { code: 38, name: 'فواتير المياه' },
      { code: 39, name: 'فواتير الاتصالات' },
      { code: 40, name: 'الإيجارات' },
      { code: 41, name: 'أجور النقل والمواصلات' },
      { code: 42, name: 'الدعاية والإعلان' },
      { code: 43, name: 'الرواتب' },
      { code: 44, name: 'الرعاية الصحية' },
      { code: 45, name: 'المنظفات' },
      { code: 46, name: 'الضيافة' },
      { code: 47, name: 'مواد التغليف' },
      { code: 48, name: 'تذاكر السفر' },
      { code: 49, name: 'عمولات شراء الأسماك' },
      { code: 50, name: 'المستهلكات' },
    ];
    await ExpenseCategory.bulkCreate(categories.map(c => ({ ...c, is_active: true })));
  },
  down: async () => {
    await ExpenseCategory.destroy({ where: {}, truncate: true });
  },
};
